// src/ui/Beehive.svelte
<script lang="ts">
  import '@xyflow/svelte/dist/style.css'

  import {
    Background,
    Controls,
    MiniMap,
    SvelteFlow,
    addEdge,
    type Connection,
  } from '@xyflow/svelte'

  import type { HiveDoc } from '../nodes/HiveDoc'
  import { nodeTypes } from '../nodes/nodeTypes'

  export let hiveDoc: HiveDoc

  function handleConnect(connection: Connection) {
    addEdge(connection, hiveDoc.edges)
  }

  function handleDump() {
    console.log(hiveDoc.nodes, hiveDoc.edges)
  }
</script>

<div class="beehive-flow">
  <SvelteFlow
    class="beehive-flow__canvas"
    nodes={hiveDoc.nodes}
    edges={hiveDoc.edges}
    {nodeTypes}
    fitView={true}
    proOptions={{ hideAttribution: true }}
    onconnect={handleConnect}
  >
    <MiniMap />
    <Controls />
    <Background gap={16} size={1} />
  </SvelteFlow>

  <button type="button" class="beehive-dump" on:click={handleDump}>
    Dump flow
  </button>
</div>

<style>
  :global(html, body, #root) {
    height: 100%;
  }

  :global(body) {
    margin: 0;
  }

  .beehive-flow {
    width: 100%;
    height: 100vh;
    position: relative;
  }

  :global(.beehive-flow__canvas) {
    width: 100%;
    height: 100%;
  }

  .beehive-dump {
    position: absolute;
    top: 12px;
    right: 12px;
    z-index: 10;
    padding: 6px 10px;
    font-size: 0.85rem;
    border-radius: 4px;
    border: 1px solid #ffd479;
    background: #fff5cc;
    cursor: pointer;
  }
</style>

// src/ui/Beehive.tsx
import { useCallback, useState } from 'react'
import {
  Background,
  Controls,
  MiniMap,
  ReactFlow,
  ReactFlowProvider,
  useReactFlow,
  applyNodeChanges,
  applyEdgeChanges,
  addEdge,
  type Edge,
  type Node,
  type NodeChange,
  type EdgeChange,
  type Connection,
} from '@xyflow/react'
import '@xyflow/react/dist/style.css'

import './Beehive.css'

import { nodeTypes } from '../nodes/nodeTypes'
import type { HiveDoc } from '../nodes/HiveDoc'

type BeehiveProps = {
  hiveDoc: HiveDoc
}

function Beehive({ hiveDoc }: BeehiveProps) {
  return (
    <ReactFlowProvider>
      <BeehiveInner hiveDoc={hiveDoc} />
    </ReactFlowProvider>
  )
}

function BeehiveInner({ hiveDoc }: BeehiveProps) {
  const reactFlowInstance = useReactFlow()

  const [nodes, setNodes] = useState<Node[]>(hiveDoc.nodes)
  const [edges, setEdges] = useState<Edge[]>(hiveDoc.edges)

  const onNodesChange = useCallback(
    (changes: NodeChange<Node>[]) => {
      setNodes((snapshot) => applyNodeChanges<Node>(changes, snapshot))
    },
    [],
  )
  const onEdgesChange = useCallback(
    (changes: EdgeChange[]) => {
      setEdges((snapshot) => applyEdgeChanges(changes, snapshot))
    },
    [],
  )
  const onConnect = useCallback(
    (connection: Connection) => {
      setEdges((snapshot) => addEdge(connection, snapshot))
    },
    [],
  )
  const handleDump = useCallback(() => {
    console.log(reactFlowInstance.toObject())
  }, [reactFlowInstance])

  return (
    <div className="beehive-flow">
      <ReactFlow
        nodes={nodes}
        edges={edges}
        fitView
        nodeTypes={nodeTypes}
        proOptions={{ hideAttribution: true }}
        style={{ width: '100%', height: '100%' }}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onConnect={onConnect}
      >
        <MiniMap />
        <Controls />
        <Background gap={16} size={1} />
      </ReactFlow>
      <button type="button" className="beehive-dump" onClick={handleDump}>
        Dump flow
      </button>
    </div>
  )
}

export default Beehive
